#!/bin/sh

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst

php_cf="/etc/yubico/val/config-db.php"
cfg_cf="/etc/yubico/val/config-db.cfg"

# PHP include
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_generate_include=php:$php_cf
dbc_go yubikey-val $@

if [ `ykval-export-clients 2>/dev/null|grep -c ','` -eq 0 ]; then
    #No clients, create one
    if `ykval-gen-clients --urandom >/dev/null 2>&1`; then
        db_input high yubikey-val/initial-client || true
        db_go
    fi
fi

if [ -d /etc/apache2/conf.d ] && [ ! -e /etc/apache2/conf.d/yubikey-val.conf ]; then
    ln -s ../../yubico/val/apache.conf /etc/apache2/conf.d/yubikey-val.conf
fi

if [ -f /etc/init.d/apache2 ] ; then
    if [ -x /usr/sbin/invoke-rc.d ]; then
        invoke-rc.d apache2 reload 3>/dev/null || true
    else
        /etc/init.d/apache2 reload 3>/dev/null || true
    fi
fi

#DEBHELPER#

exit 0
