#!/bin/sh

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst

# https://www.debian.org/doc/manuals/developers-reference/ch06.en.html#bpp-debian-maint-scripts
pathfind() {
    OLDIFS="$IFS"
    IFS=:
    for p in $PATH; do
        if [ -x "$p/$*" ]; then
            IFS="$OLDIFS"
            return 0
        fi
    done
    IFS="$OLDIFS"
    return 1
}

php_cf="/etc/yubico/val/config-db.php"
cfg_cf="/etc/yubico/val/config-db.cfg"

# PHP include
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_generate_include=php:$php_cf
dbc_go yubikey-val $@

if [ `ykval-export-clients 2>/dev/null|grep -c ','` -eq 0 ]; then
    #No clients, create one
    ykval-gen-clients --urandom >/dev/null 2>&1 || true
fi

#Apache configuration
if [ "$1" = "configure" ] ; then
    CONF="yubikey-val"

    # apache 2.4
    if [ -d /etc/apache2/conf-enabled ]; then
        ln -sf ../../yubico/val/apache-2.4.conf /etc/apache2/conf-available/$CONF.conf
        ln -sf ../conf-available/$CONF.conf /etc/apache2/conf-enabled/$CONF.conf
    fi

    # apache 2.2
    if [ -d /etc/apache2/conf.d ]; then
        ln -sf ../../yubico/val/apache-2.2.conf /etc/apache2/conf.d/$CONF.conf
    fi

    if [ -f /etc/init.d/apache2 ] ; then
        if pathfind invoke-rc.d; then
            invoke-rc.d apache2 reload 3>/dev/null || true
        else
            /etc/init.d/apache2 reload 3>/dev/null || true
        fi
    fi
fi

#DEBHELPER#

exit 0
